apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ${NAME}
  annotations:
    description: "Caseflow -Web"
    tags: "caseflow-web"
    iconClass: icon-js
labels:
  app: ${NAME}-${COMPONENT}
  app.kubernetes.io/part-of: ${NAME}-${COMPONENT}
parameters:
- name: NAME
  description: Module name
  value: caseflow
- name: COMPONENT
  description: Component name
  value: caseflow-web
- name: IMAGE_TAG
  description: Image tag to use
  value: latest
- name: DOMAIN
  value: apps.silver.devops.gov.bc.ca
- name: CPU_REQUEST
  value: "125m"
- name: MEMORY_REQUEST
  value: "150Mi"
- name: CPU_LIMIT
  value: "275m"
- name: MEMORY_LIMIT
  value: "450Mi"
- name: MIN_REPLICAS
  description: The minimum amount of replicas
  value: "1"
- name: MAX_REPLICAS
  description: The maximum amount of replicas
  value: "3"
- name: CONTAINER_PORT
  description: The port on which the application will be accessible
  required: true
- name: REGISTRY
  description: Container registry to import from (internal is image-registry.openshift-image-registry.svc:5000)
  value: ghcr.io #
- name: PROMOTE
  description: Image (namespace/name:tag) to promote/import
  value: aot-technologies/case-flow-ai-case-management/app/caseflow_web
- name: ENV
  description: The Environment on which it is deployed
  required: true
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: caseflow-config
    data:
      config.js: |-
        // runtime-config.js vars
          window["_env_"] =  {
            "REACT_APP_KEYCLOAK_WEB_CLIENTID": "case-flow-web",
            "REACT_APP_KEYCLOAK_URL_REALM": "forms-flow-ai",
            # "REACT_APP_AUTH_CLIENT_ID": "${REACT_APP_AUTH_CLIENT_ID}",
            "REACT_APP_KEYCLOAK_URL": "https://forms-flow-idm-caseflow.aot-technologies.com",            
            "REACT_APP_CASEFLOW_API_URL": "https://caseflow-core.aot-technologies.com",
            "REACT_APP_CASEFLOW_GRAPHQL_API_URL": "https://caseflow-gateway.aot-technologies.com",
            "REACT_APP_CASEFLOW_DMS": "1",
            "APPLICATION_NAME": "caseflow.ai",            
            "REACT_APP_CASEFLOW_LOB_GRAPHQL_API_URL": "https://caseflow-lob.aot-technologies.com",
            "REACT_APP_PAGINATION_TAKE": "10",  
            "REACT_APP_FORMSFLOW_URL": "true",
            "REACT_APP_FORMSFLOW_WEB_URL": "https://forms-flow-bpm-caseflow.aot-technologies.com",
            "REACT_APP_FORMSFLOW_APP_URL": "https://forms-flow-forms-caseflow.aot-technologies.com",
            "REACT_APP_CASEFLOW_DMS_API_URL": "https://caseflow-dms.aot-technologies.com",
            "REACT_APP_FORMSFLOW_FORM_URL": "https://forms-flow-api-caseflow.aot-technologies.com",
            "REACT_APP_FORMSFLOW_WEB_URL": "https://forms-flow-web-caseflow.aot-technologies.com",
            "REACT_APP_GENERIC_NAME": "Case"


          }
  - apiVersion: v1
    kind: ImageStream
    metadata:
      labels:
        app: ${NAME}-${COMPONENT}
      name: ${NAME}-${COMPONENT}
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: ${IMAGE_TAG}
          from:
            kind: DockerImage
            name: ${REGISTRY}/${PROMOTE}:${IMAGE_TAG}
          referencePolicy:
            type: Local
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      labels:
        app: ${NAME}-${COMPONENT}
      name: ${NAME}-${COMPONENT}
    spec:
      replicas: 1
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - ${NAME}-${COMPONENT}
            from:
              kind: ImageStreamTag
              name: ${NAME}-${COMPONENT}:${IMAGE_TAG}
      selector:
        deploymentconfig: ${NAME}-${COMPONENT}
      strategy:
        type: Rolling
      template:
        metadata:
          labels:
            app: ${NAME}-${COMPONENT}
            deploymentconfig: ${NAME}-${COMPONENT}
        spec:
          containers:
            - image: " "
              imagePullPolicy: Always
              name: ${NAME}-${COMPONENT}
              env:
                - name: REACT_APP_KEYCLOAK_WEB_CLIENTID
                  valueFrom:
                    configMapKeyRef:
                      name: caseflow-configmap
                      key: REACT_APP_KEYCLOAK_WEB_CLIENTID
                
                              
              ports:
                - containerPort: ${{CONTAINER_PORT}}
                  protocol: TCP
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
              # readinessProbe:
              #   tcpSocket:
              #     path: /
              #     port: ${{CONTAINER_PORT}}
              #     scheme: HTTP
              #   initialDelaySeconds: 10
              #   periodSeconds: 30
              #   timeoutSeconds: 5
              #   failureThreshold: 30
              #   successThreshold: 1
              # livenessProbe:
              #   successThreshold: 1
              #   failureThreshold: 3
              #   httpGet:
              #     path: /
              #     port: ${{CONTAINER_PORT}}
              #     scheme: HTTP
              #   initialDelaySeconds: 10
              #   periodSeconds: 30
              #   timeoutSeconds: 5
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: ${NAME}-${COMPONENT}
      name: ${NAME}-${COMPONENT}
    spec:
      ports:
        - name: ${CONTAINER_PORT}-tcp
          protocol: TCP
          port: 80
          targetPort: ${{CONTAINER_PORT}}
      selector:
        deploymentconfig: ${NAME}-${COMPONENT}
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: ${NAME}-${COMPONENT}
      name: ${NAME}-${COMPONENT}
    spec:
      host: ${NAME}-${COMPONENT}-${ENV}.${DOMAIN}
      port:
        targetPort: ${CONTAINER_PORT}-tcp
      to:
        kind: Service
        name: ${NAME}-${COMPONENT}
        weight: 100
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
  - apiVersion: autoscaling/v2
    kind: HorizontalPodAutoscaler
    metadata:
      name: "${NAME}-${COMPONENT}"
    spec:
      scaleTargetRef:
        apiVersion: apps.openshift.io/v1
        kind: DeploymentConfig
        name: "${NAME}-${COMPONENT}"
      minReplicas: ${{MIN_REPLICAS}}
      maxReplicas: ${{MAX_REPLICAS}}
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 100